### ISSUE TITLE
Publish on mqtt too

### ISSUE THREAD

**Issue by Boburshoh-oss** [lbt/channels-mqtt-proxy#1]
# Receive message from WebSocket
    async def receive(self, text_data):

        ... # existing group_send etc

        # Publish on mqtt too
        await self.channel_layer.send(
            "mqtt",
            {
                "type": "mqtt_publish",
                "publish": {  # These form the kwargs for mqtt.publish
                    "topic":  f"chat/{self.room_name}_out",
                    "payload": message,
                    "qos": 2,
                    "retain": False,
                    }
        })

I can't listen across a mqttbox with mosquitto. And command "py manga.py runworker mqtt" didn't work and this being just pass! 
How can I use, help me

**Comment by lbt** [comment]
Have you got the tutorial working: 
https://github.com/lbt/channels-mqtt-proxy/tree/main/examples

**Comment by lbt** [comment]
No response. Closing
